ALTER TABLE chamado
ADD COLUMN cpf VARCHAR(100) DEFAULT NULL,
ADD COLUMN nome_mae VARCHAR(100) DEFAULT NULL,
ADD COLUMN data_admin VARCHAR(100) DEFAULT NULL,
ADD COLUMN data_nasc VARCHAR(100) DEFAULT NULL,
ADD COLUMN funcao VARCHAR(100) DEFAULT NULL;
